### ISSUE TITLE
Unable to perform 'TAL -> MNI Batch Convert' in 'The MNI <-> Talairach Tool'

### ISSUE THREAD

**Issue by H160040** [bioimagesuiteweb/bisweb-manual#1]
Hi, I am unable to perform 'TAL -> MNI Batch Convert' in 'The MNI <-> Talairach Tool'.

I submitted a list of Talairach coordinates (one point per line, i.e. x, y and z coordinates per row, in .csv file) to convert a batch of Talairach coordinates into their respective MNI coordinates. However, the Batch Convert only recognizes the first line (the first row of the .csv file). It only converts the first line of Talairach coordinates into MNI coordinates. 

Any Talairach coordinates after the first line were not recognized, and thus not converted into MNI coordinates. Please advice how can I perform TAL -> MNI conversion for a list of Talairach coordinates? 

Look forward to hear from you soon, thank you!

**Comment by XeniosP** [comment]
Could you please provide the file you were using? This will help us debug the issue.

**Comment by H160040** [comment]
Thank you for your fast response!

I am unable to attach the .csv file. Hence, please find the Talairach coordinates in .xlsx file as attached.
[Talairach coordinates.xlsx](https://github.com/bioimagesuiteweb/bisweb-manual/files/4960521/Talairach.coordinates.xlsx)

**Comment by XeniosP** [comment]
Will take a look later today.

**Comment by H160040** [comment]
Thank you, I look forward to hear from you soon!

**Comment by H160040** [comment]
Hi, I just tried again and I am able to perform batch conversion now. I have absolutely no clue what happen previously. Nevertheless, thank you for your time and the software - it's indeed helpful! Have a good day ahead! Best wishes
